### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/Build-responsive-design#2]
Leave some tips for us please

**Comment by nyatindopatrick** [comment]
Great job!
To fix the box header image responsiveness, please try this:  
.box-header > img {
    width: 5%;
    margin: -100px 5px 0px;
    position: absolute;
}

**Comment by Kyle-Law** [comment]
References of what I did for the image issue:
**1 ) Move img as the first child of the `.box-header` class**
`<div class="box-header">
    		<img src="https://img-cdn.tnwcdn.com/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1169455071161180161%2FRWzd6q3T.png&amp;signature=9abfd1b56a649808dfe655c8baae4a81" alt="box-image">
            <h4>Fruitas Holdig Inc</h4>
            <div class="price-tag">
              <h4>$100M</h4>
              <span>EQUITY CROWDFUNDING</span>
            </div>
            </div>`

**2) Give `float:left` property to the img**
`.box-header > img {
    width: 25%;
    float: left;
    margin: 10px;
}`

**Comment by dili021** [comment]
good work so far!
-Just a heads up regarding article tags. It won't pass the validator without heading tags also. Same goes for sections.
-I am curious about using ul/li in the box image of the fourth-section grid?
That's about it for now, curious to see how it goes with the responsiveness.
Good luck!

**Comment by patriciachrysy** [comment]
Thank you guys
